image: registry.gitlab.com/swirlycloud/swirly-docker/toolchain:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SWIRLY_BUILD_ARCH: haswell
  SWIRLY_BUILD_SHARED: 'ON'
  SWIRLY_INSTALL_PREFIX: /opt/swirlycloud
  VERBOSE: 1

stages:
  - check
  - build

check-cppcheck:
  stage: check
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -G 'Unix Makefiles'
  script:
    - make -j2 cppcheck

build-debug-clang:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -G 'Unix Makefiles'
      -DSWIRLY_BUILD_ARCH=$SWIRLY_BUILD_ARCH
      -DSWIRLY_BUILD_SHARED=$SWIRLY_BUILD_SHARED
      -DCMAKE_BUILD_TYPE=DEBUG
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DCMAKE_INSTALL_PREFIX=$SWIRLY_INSTALL_PREFIX
  script:
    - make -j2 all test swift

build-release-clang:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -G 'Unix Makefiles'
      -DSWIRLY_BUILD_ARCH=$SWIRLY_BUILD_ARCH
      -DSWIRLY_BUILD_SHARED=$SWIRLY_BUILD_SHARED
      -DCMAKE_BUILD_TYPE=RELEASE
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DCMAKE_INSTALL_PREFIX=$SWIRLY_INSTALL_PREFIX
  script:
    - make -j2 all test swift package
  artifacts:
    paths:
      - 'build/*.rpm'
      - 'build/*.tar.gz'
    expire_in: 2 days

build-debug-gcc:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -G 'Unix Makefiles'
      -DSWIRLY_BUILD_ARCH=$SWIRLY_BUILD_ARCH
      -DSWIRLY_BUILD_SHARED=$SWIRLY_BUILD_SHARED
      -DCMAKE_BUILD_TYPE=DEBUG
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DCMAKE_INSTALL_PREFIX=$SWIRLY_INSTALL_PREFIX
  script:
    - make -j2 all test swift

build-release-gcc:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -G 'Unix Makefiles'
      -DSWIRLY_BUILD_ARCH=$SWIRLY_BUILD_ARCH
      -DSWIRLY_BUILD_SHARED=$SWIRLY_BUILD_SHARED
      -DCMAKE_BUILD_TYPE=RELEASE
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DCMAKE_INSTALL_PREFIX=$SWIRLY_INSTALL_PREFIX
  script:
    - make -j2 all test swift package
  artifacts:
    paths:
      - 'build/*.rpm'
      - 'build/*.tar.gz'
    expire_in: 2 days
