image: registry.gitlab.com/swirlycloud/swirly-docker/toolchain:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build-debug-clang:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -G "Unix Makefiles"
      -DCMAKE_BUILD_TYPE=DEBUG
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DSWIRLY_BUILD_SHARED=ON
  script:
    - make -j2 all test swift

build-release-clang:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -G "Unix Makefiles"
      -DCMAKE_BUILD_TYPE=RELEASE
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DSWIRLY_BUILD_SHARED=ON
  script:
    - make -j2 all test swift

build-debug-gcc:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -G "Unix Makefiles"
      -DCMAKE_BUILD_TYPE=DEBUG
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DSWIRLY_BUILD_SHARED=ON
  script:
    - make -j2 all test swift

build-release-gcc:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
    - cmake .. -G "Unix Makefiles"
      -DCMAKE_BUILD_TYPE=RELEASE
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DSWIRLY_BUILD_SHARED=ON
  script:
    - make -j2 all test swift
