language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - travis-ci/sqlite3
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-6.0
            - cmake
            - cmake-data
            - g++-8
            - libsqlite3-dev
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=clang-6.0
        - CMAKE_CXX_COMPILER=clang++-6.0
        - SWIRLY_BUILD_SHARED=ON

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - travis-ci/sqlite3
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-6.0
            - cmake
            - cmake-data
            - g++-8
            - libsqlite3-dev
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=clang-6.0
        - CMAKE_CXX_COMPILER=clang++-6.0
        - SWIRLY_BUILD_SHARED=ON

    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - travis-ci/sqlite3
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-8
            - libsqlite3-dev
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=gcc-8
        - CMAKE_CXX_COMPILER=g++-8
        - SWIRLY_BUILD_SHARED=ON

    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - travis-ci/sqlite3
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-8
            - libsqlite3-dev
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=gcc-8
        - CMAKE_CXX_COMPILER=g++-8
        - SWIRLY_BUILD_SHARED=ON

before_install:
  - sudo add-apt-repository -y ppa:samuel-bachmann/boost
  - sudo add-apt-repository -y ppa:dluxen/flatbuffers
  - sudo apt-get update || true
  - sudo apt-get install flatbuffers libboost-date-time1.60-dev
                         libboost-filesystem1.60-dev libboost-test1.60-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
          -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
          -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
          -DSWIRLY_BUILD_SHARED=${SWIRLY_BUILD_SHARED}
          ..

script:
  - make -j2
  - make test

after_failure:
  - cat Testing/Temporary/LastTest.log
