language: cpp

sudo: false

os:
  - linux
  - osx

compiler:
  - clang++
  - g++

addons:
  apt:
    sources:
      - boost-latest
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - clang-3.8
      - g++-5
      - libboost1.55-all-dev

matrix:
  exclude:
    - os: osx
      compiler: g++

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install llvm37;
      brew outdated boost || brew upgrade boost;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CXX" = "clang++" ]; then
        export CXX=clang++-3.8 CC=clang-3.8;
      elif [ "$CXX" = "g++" ]; then
        export CXX=g++-5 CC=gcc-5;
      fi;
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export CXX=clang++-3.7 CC=clang-3.7;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
